[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --worker-class eventlet -w 1 wsgi:app"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.9.16" 
